apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  namespace: hotstar
  labels:
    app: hotstar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
        - name: hotstar
          image: neeraj2806/new-hotstar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
