name: CICD pipeline for hotstar app
on: 
  push:
    branches:
     - main
  pull_request:
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    #1 Checkout code
      - name: checkout code
        uses: actions/checkout@v3
    #2 Set up nodejs
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
           node-version: "23"
    #3 Install nodejs dependencies
      - name: install dependencies
        run: npm install
    #4 Sonarqube Scan
      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
         projectBaseDir: .
         projectKey: Hotstar
         projectName: Hotstar
        env:
           SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #5 login to docker hub
      - name: login to docker hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
    #6 build docker image
      - name: building docker image 
        run: docker build -t ${{ secrets.DOCKER_USER }}/hotstar:${{ github.sha }}
         
